spring:
  application:
    name: TaskTracker
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true